using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http.Json;
using System.Threading.Tasks;
using ClinicManagement.Application.Common.Models;
using ClinicManagement.Application.Mpi.DTOs;
using ClinicManagement.Domain.Enums;
using Xunit;

namespace ClinicManagement.IntegrationTests;

public class MasterPatientIndexTests : IntegrationTestBase
{
    public MasterPatientIndexTests(CustomWebApplicationFactory factory) : base(factory) { }

    [Fact]
    public async Task Receptionist_Can_Register_WalkIn_Patient_With_AutoGenerated_MRN()
    {
        await AuthenticateAsync("rec@test.com");

        var walkInReq = new RegisterWalkInPatientRequest
        {
            FullName = "Nguyễn Văn Cấp Cứu",
            PhoneNumber = "0988776655",
            Gender = Gender.Male,
            DateOfBirth = new DateOnly(1985, 5, 20),
            Address = "Số 45 Đường Y, Phường X",
            NationalId = "079085001234",
            BhytNumber = "GD4790123456789",
            BloodType = "O",
            RhFactor = "+",
            Allergies = new List<CreatePatientAllergyRequest>
            {
                new()
                {
                    AllergenType = AllergenType.Drug,
                    AllergenName = "Penicillin",
                    Severity = AllergySeverity.Severe,
                    ReactionDescription = "Sốc phản vệ độ 2"
                }
            },
            EmergencyContact = new EmergencyContactDto
            {
                FullName = "Trần Thị Người Nhà",
                Relationship = "Vợ",
                PhoneNumber = "0977665544",
                Address = "Cùng địa chỉ"
            }
        };

        var res = await Client.PostAsJsonAsync("/api/v1/mpi/patients/walk-in", walkInReq);
        Assert.Equal(HttpStatusCode.Created, res.StatusCode);

        var created = await res.Content.ReadFromJsonAsync<ApiResponse<MpiPatientDto>>();
        Assert.NotNull(created?.Data);
        Assert.StartsWith("MRN-", created.Data.MedicalRecordNumber);
        Assert.Equal("Nguyễn Văn Cấp Cứu", created.Data.FullName);
        Assert.Equal("079085001234", created.Data.NationalId);
        Assert.Single(created.Data.Allergies);
        Assert.Equal("Penicillin", created.Data.Allergies[0].AllergenName);
        Assert.Single(created.Data.EmergencyContacts);
        Assert.Equal("Trần Thị Người Nhà", created.Data.EmergencyContacts[0].FullName);

        // Verify Search by MRN
        var searchRes = await Client.GetAsync($"/api/v1/mpi/patients/by-mrn/{created.Data.MedicalRecordNumber}");
        Assert.Equal(HttpStatusCode.OK, searchRes.StatusCode);
        var foundByMrn = await searchRes.Content.ReadFromJsonAsync<ApiResponse<MpiPatientDto>>();
        Assert.NotNull(foundByMrn?.Data);
        Assert.Equal(created.Data.Id, foundByMrn.Data.Id);

        // Verify Search via Query
        var queryRes = await Client.GetAsync($"/api/v1/mpi/patients?nationalId=079085001234");
        Assert.Equal(HttpStatusCode.OK, queryRes.StatusCode);
        var queryResult = await queryRes.Content.ReadFromJsonAsync<ApiResponse<PagedResult<MpiPatientDto>>>();
        Assert.NotNull(queryResult?.Data);
        Assert.NotEmpty(queryResult.Data.Items);
    }

    [Fact]
    public async Task Duplicate_NationalId_Registration_Throws_Conflict()
    {
        await AuthenticateAsync("rec@test.com");

        var nid = "079099009999";
        var firstReq = new RegisterWalkInPatientRequest
        {
            FullName = "Bệnh Nhân A",
            NationalId = nid
        };
        var firstRes = await Client.PostAsJsonAsync("/api/v1/mpi/patients/walk-in", firstReq);
        Assert.Equal(HttpStatusCode.Created, firstRes.StatusCode);

        var secondReq = new RegisterWalkInPatientRequest
        {
            FullName = "Bệnh Nhân B Trùng CCCD",
            NationalId = nid
        };
        var secondRes = await Client.PostAsJsonAsync("/api/v1/mpi/patients/walk-in", secondReq);
        Assert.Equal(HttpStatusCode.Conflict, secondRes.StatusCode);
    }

    [Fact]
    public async Task Staff_Can_Add_And_Remove_Patient_Allergy()
    {
        await AuthenticateAsync("rec@test.com");

        var walkInReq = new RegisterWalkInPatientRequest
        {
            FullName = "Lê Thị Dị Ứng",
            PhoneNumber = "0911223344"
        };
        var res = await Client.PostAsJsonAsync("/api/v1/mpi/patients/walk-in", walkInReq);
        var created = await res.Content.ReadFromJsonAsync<ApiResponse<MpiPatientDto>>();
        Assert.NotNull(created?.Data);
        var patientId = created.Data.Id;

        // Add Allergy
        var addAllergyReq = new CreatePatientAllergyRequest
        {
            AllergenType = AllergenType.Food,
            AllergenName = "Hải sản / Tôm cua",
            Severity = AllergySeverity.Moderate,
            ReactionDescription = "Mẩn ngứa toàn thân"
        };
        var allergyRes = await Client.PostAsJsonAsync($"/api/v1/mpi/patients/{patientId}/allergies", addAllergyReq);
        Assert.Equal(HttpStatusCode.OK, allergyRes.StatusCode);
        var addedAllergy = await allergyRes.Content.ReadFromJsonAsync<ApiResponse<PatientAllergyDto>>();
        Assert.NotNull(addedAllergy?.Data);
        var allergyId = addedAllergy.Data.Id;

        // Delete Allergy
        var deleteRes = await Client.DeleteAsync($"/api/v1/mpi/patients/{patientId}/allergies/{allergyId}");
        Assert.Equal(HttpStatusCode.OK, deleteRes.StatusCode);

        // Verify removed
        var getPatientRes = await Client.GetAsync($"/api/v1/mpi/patients/{patientId}");
        var patientAfter = await getPatientRes.Content.ReadFromJsonAsync<ApiResponse<MpiPatientDto>>();
        Assert.NotNull(patientAfter?.Data);
        Assert.Empty(patientAfter.Data.Allergies);
    }
}
