using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace ClinicManagement.AI.Training;

/// <summary>Offline text augmentation only; never invokes a model or provider.</summary>
public static class RoleIntentDatasetGenerator
{
    public const string GeneratorVersion = "role-intent-gen-v1";
    public const int RngSeed = 20261002;
    public const string SeedsFile = "role_intent_seeds_v1.tsv";
    public const string LabelsFile = "role_intent_labels_v1.json";
    public const string TrainFile = "role_intent_train_v1.json";
    public const string ValidationFile = "role_intent_validation_v1.json";
    public const string ManifestFile = "role_intent_manifest_v1.json";
    public const string Provenance = "Seeds generated by AI (Claude), reviewed and edited by the project author (rows with nguon=claude_v1_sua). Not a blind test set.";

    public static readonly IReadOnlyDictionary<string, string> RoleCodes = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["BenhNhan"] = "Patient", ["LeTan"] = "Receptionist", ["BacSi"] = "Doctor",
        ["KTV"] = "DiagnosticTechnician", ["DuocSi"] = "Pharmacist", ["Admin"] = "Admin"
    };

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };
    private static readonly Regex AppointmentCode = new(@"lh[- ]?\d{3,}", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    private static readonly (string Pattern, string Replacement)[] Abbreviations =
    {
        (@"không|khong", "ko"), (@"được|duoc", "dc"), (@"bệnh nhân|benh nhan", "bn"),
        (@"danh sách|danh sach", "ds"), (@"số lượng|so luong", "sl"), (@"xét nghiệm|xet nghiem", "xn"),
        (@"kết quả|ket qua", "kq"), (@"gì|gi", "j"), (@"rồi|roi", "r"), (@"vậy|vay", "v"), (@"với|voi", "vs")
    };
    private static readonly string[] Prefixes = { "cho hỏi ", "cho mình hỏi ", "ơi " };
    private static readonly string[] Suffixes = { " ạ", " nhé", " với", " giúp mình" };

    public static IReadOnlyList<RoleIntentLabel> ReadLabels(string dataDirectory) =>
        JsonSerializer.Deserialize<List<RoleIntentLabel>>(File.ReadAllText(Path.Combine(dataDirectory, LabelsFile)), JsonOptions)
        ?? throw new InvalidDataException("Empty label catalog.");

    public static IReadOnlyList<RoleIntentSeed> ReadSeeds(string dataDirectory)
    {
        var lines = File.ReadAllLines(Path.Combine(dataDirectory, SeedsFile), Encoding.UTF8);
        if (lines.Length == 0 || lines[0] != "vai_tro\tcau\tnhan\tnguon")
            throw new InvalidDataException("Unexpected TSV header.");
        var counters = new Dictionary<string, int>(StringComparer.Ordinal);
        var seeds = new List<RoleIntentSeed>();
        for (var index = 1; index < lines.Length; index++)
        {
            var columns = lines[index].Split('\t');
            if (columns.Length != 4 || columns.Any(string.IsNullOrWhiteSpace))
                throw new InvalidDataException($"Invalid seed row {index + 1}.");
            var ordinal = counters.GetValueOrDefault(columns[2]) + 1;
            counters[columns[2]] = ordinal;
            seeds.Add(new($"RI-{columns[2]}-{ordinal:D2}", columns[0], columns[1], columns[2], columns[3]));
        }
        return seeds;
    }

    /// <param name="dataDirectory">Directory containing the seeds and label catalog.</param>
    /// <param name="outputDirectory">Optional separate destination for the three generated files.</param>
    public static RoleIntentManifest Generate(string dataDirectory, string? outputDirectory = null)
    {
        var labels = ReadLabels(dataDirectory);
        var seeds = ReadSeeds(dataDirectory);
        var catalog = labels.ToDictionary(x => x.Label, StringComparer.Ordinal);
        var owners = new Dictionary<string, string>(StringComparer.Ordinal);
        // Reserve every original before augmentation: a variant cannot displace a later seed.
        foreach (var seed in seeds)
        {
            if (!catalog.TryGetValue(seed.Label, out var definition) ||
                (seed.Role == "Chung" ? definition.Group != "Shared" || !RoleCodes.Values.All(definition.Roles.Contains)
                    : !RoleCodes.TryGetValue(seed.Role, out var role) || !definition.Roles.Contains(role)))
                throw new InvalidDataException($"Invalid role/label on {seed.SeedId}.");
            var normalized = Normalize(seed.Text);
            if (owners.TryGetValue(normalized, out var owner) && owner != seed.Label)
                throw new InvalidDataException($"Original seeds collide across labels: {owner} / {seed.Label}: {seed.Text}");
            owners[normalized] = seed.Label;
        }

        var random = new Random(RngSeed);
        var augmented = new List<(RoleIntentSeed Seed, List<(string Variant, string Text)> Candidates)>();
        var dropped = 0;
        foreach (var seed in seeds)
        {
            var retained = new List<(string Variant, string Text)>();
            var exact = new HashSet<string>(StringComparer.Ordinal);
            foreach (var candidate in Candidates(seed, random))
            {
                var text = candidate.Text;
                if (seed.Label == "LookupAppointment" && candidate.Variant != "original")
                    text = ReplaceAppointmentCode(text, random);
                if (seed.Label == "LookupAppointment" && !AppointmentCode.IsMatch(text))
                    throw new InvalidDataException($"Missing appointment code: {seed.SeedId}");
                if (!exact.Add(text)) continue;
                var normalized = Normalize(text);
                if (owners.TryGetValue(normalized, out var owner) && owner != seed.Label)
                {
                    dropped++;
                    continue;
                }
                owners[normalized] = seed.Label;
                retained.Add((candidate.Variant, text));
                if (retained.Count == 12) break;
            }
            augmented.Add((seed, retained));
        }

        var validationSeedIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var group in seeds.GroupBy(x => x.Label))
        {
            var shuffled = group.ToArray();
            if (shuffled.Length < 3) throw new InvalidDataException($"Too few seeds for {group.Key}.");
            for (var index = shuffled.Length - 1; index > 0; index--)
            {
                var other = random.Next(index + 1);
                (shuffled[index], shuffled[other]) = (shuffled[other], shuffled[index]);
            }
            foreach (var seed in shuffled.Take(2)) validationSeedIds.Add(seed.SeedId);
        }

        var records = new List<RoleIntentRecord>();
        foreach (var (seed, candidates) in augmented)
        {
            var split = validationSeedIds.Contains(seed.SeedId) ? "validation" : "train";
            for (var index = 0; index < candidates.Count; index++)
                records.Add(new($"{seed.SeedId}-V{index + 1:D2}", seed.SeedId,
                    seed.Role == "Chung" ? "Chung" : RoleCodes[seed.Role], seed.Label,
                    candidates[index].Text, split, candidates[index].Variant, seed.Source));
        }

        var train = records.Where(x => x.Split == "train").ToArray();
        var validation = records.Where(x => x.Split == "validation").ToArray();
        var destination = outputDirectory ?? dataDirectory;
        Directory.CreateDirectory(destination);
        WriteJson(Path.Combine(destination, TrainFile), train);
        WriteJson(Path.Combine(destination, ValidationFile), validation);
        var hashes = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [SeedsFile] = FileSha256(Path.Combine(dataDirectory, SeedsFile)),
            [LabelsFile] = FileSha256(Path.Combine(dataDirectory, LabelsFile)),
            [TrainFile] = FileSha256(Path.Combine(destination, TrainFile)),
            [ValidationFile] = FileSha256(Path.Combine(destination, ValidationFile))
        };
        var counts = labels.Select(x => new RoleIntentLabelCount(x.Label,
            train.Count(r => r.Label == x.Label), validation.Count(r => r.Label == x.Label))).ToArray();
        var manifest = new RoleIntentManifest(GeneratorVersion, RngSeed, hashes, counts,
            new(train.Length, validation.Length, records.Count), dropped, Provenance);
        WriteJson(Path.Combine(destination, ManifestFile), manifest);
        return manifest;
    }

    private static IEnumerable<(string Variant, string Text)> Candidates(RoleIntentSeed seed, Random random)
    {
        var folded = RemoveDiacritics(seed.Text);
        yield return ("original", seed.Text);
        yield return ("accent_fold", folded);
        yield return ("lower_trim", seed.Text.ToLowerInvariant().TrimEnd('?', '.', '!'));
        foreach (var (name, text) in Abbreviate(seed.Text)) yield return (name, text);
        yield return ("typo", Typo(seed.Text, random));
        var allowAffix = seed.Label is not ("Greeting" or "OutOfScope");
        if (allowAffix) yield return ("affix", Affix(seed.Text, random));
        foreach (var (name, text) in Abbreviate(folded)) yield return ($"accent_fold_{name}", text);
        yield return ("accent_fold_typo", Typo(folded, random));
        if (allowAffix) yield return ("accent_fold_affix", Affix(folded, random));
    }

    private static IEnumerable<(string Variant, string Text)> Abbreviate(string text)
    {
        // Enumerate ko then k when applicable; replace all dictionary words in each candidate.
        var hasKhong = Regex.IsMatch(text, @"\b(?:không|khong)\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
        foreach (var khong in hasKhong ? new[] { "ko", "k" } : new[] { "ko" })
        {
            var result = text;
            foreach (var (pattern, replacement) in Abbreviations)
                result = Regex.Replace(result, $@"\b(?:{pattern})\b", pattern == "không|khong" ? khong : replacement,
                    RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
            if (result != text) yield return ($"abbreviation_{khong}", result);
        }
    }

    private static string Typo(string text, Random random)
    {
        var codes = AppointmentCode.Matches(text).Cast<Match>().ToArray();
        var words = Regex.Matches(text, @"\p{L}{4,}").Cast<Match>()
            .Where(word => !codes.Any(code => word.Index < code.Index + code.Length && code.Index < word.Index + word.Length)).ToArray();
        if (words.Length == 0) return text;
        var word = words[random.Next(words.Length)];
        var operation = random.Next(3);
        var position = random.Next(operation == 0 ? word.Length - 1 : word.Length);
        var value = word.Value;
        var changed = operation switch
        {
            0 => value[..position] + value[position + 1] + value[position] + value[(position + 2)..],
            1 => value.Remove(position, 1),
            _ => value.Insert(position, value[position].ToString())
        };
        return text[..word.Index] + changed + text[(word.Index + word.Length)..];
    }

    private static string Affix(string text, Random random)
    {
        var index = random.Next(Prefixes.Length + Suffixes.Length);
        return index < Prefixes.Length ? Prefixes[index] + text : text + Suffixes[index - Prefixes.Length];
    }

    private static string ReplaceAppointmentCode(string text, Random random)
    {
        var digits = random.Next(3, 6);
        var lower = (int)Math.Pow(10, digits - 1);
        var number = random.Next(lower, lower * 10).ToString(CultureInfo.InvariantCulture);
        var replacement = random.Next(3) switch { 0 => "LH-" + number, 1 => "LH" + number, _ => "lh " + number };
        return AppointmentCode.Replace(text, replacement);
    }

    public static string RemoveDiacritics(string text)
    {
        var builder = new StringBuilder();
        foreach (var character in text.Normalize(NormalizationForm.FormD))
            if (CharUnicodeInfo.GetUnicodeCategory(character) != UnicodeCategory.NonSpacingMark)
                builder.Append(character switch { 'đ' => 'd', 'Đ' => 'D', _ => character });
        return builder.ToString().Normalize(NormalizationForm.FormC);
    }

    public static string Normalize(string text)
    {
        var folded = RemoveDiacritics(text).ToLowerInvariant();
        var withoutPunctuation = new string(folded.Where(c => !char.IsPunctuation(c)).ToArray());
        return Regex.Replace(withoutPunctuation, @"\s+", " ").Trim();
    }

    public static string FileSha256(string path) => Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant();

    private static void WriteJson<T>(string path, T value) =>
        File.WriteAllText(path, JsonSerializer.Serialize(value, JsonOptions).Replace("\r\n", "\n") + "\n", new UTF8Encoding(false));
}

public sealed record RoleIntentLabel(string Label, string Group, string[] Roles, string? TargetTool, string Note);
public sealed record RoleIntentSeed(string SeedId, string Role, string Text, string Label, string Source);
public sealed record RoleIntentRecord(string Id, string SeedId, string Role, string Label, string Text, string Split, string Variant, string Source);
public sealed record RoleIntentLabelCount(string Label, int Train, int Validation);
public sealed record RoleIntentTotals(int Train, int Validation, int Total);
public sealed record RoleIntentManifest(string GeneratorVersion, int RngSeed, Dictionary<string, string> Sha256,
    RoleIntentLabelCount[] CountsByLabelAndSplit, RoleIntentTotals Totals, int DroppedCrossLabelCandidates, string Provenance);
